"""add_special_discount

Revision ID: 6d595812eb83
Revises: b669170a770b
Create Date: 2026-03-16 22:21:40.938501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d595812eb83'
down_revision: Union[str, None] = 'b669170a770b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_profiles', sa.Column('special_discount', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_profiles', 'special_discount')
    # ### end Alembic commands ###
