"""add_company_logo_to_user

Revision ID: b669170a770b
Revises: 524bd69a4181
Create Date: 2026-03-15 22:26:59.947397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b669170a770b'
down_revision: Union[str, None] = '524bd69a4181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('logo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_url')
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
